name: chapter_28
version: 0.0.1
author: Moises Belchin and Patricia Juberias
description: Web Programming with Dart by Moises Belchin and Patricia Juberias
homepage: http://www.apress.com/9781484205570
documentation: http://blogdart.es/
#dev_dependencies:
#  unittest: any
