name: chapter_29
version: 0.0.1
author: Moises Belchin and Patricia Juberias
description: Web Programming with Dart by Moises Belchin and Patricia Juberias
homepage: http://www.apress.com/9781484205570
documentation: http://blogdart.es/
dependencies:
    polymer: ">=0.12.0 <0.13.0"
transformers:
- polymer:
    entry_points: web/chapter_29.html
